services:

  mysql:
    build:
      context: .
      dockerfile: mysql/Dockerfile

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - devops-net

    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping -h localhost -u root -p"$MYSQL_ROOT_PASSWORD"']
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 20s


  flask-blue:
    build: .
    restart: unless-stopped

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - devops-net


  flask-green:
    build: .
    restart: unless-stopped

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
   
    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - devops-net


  nginx:
    build: ./nginx
    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - flask-blue
      - flask-green

    networks:
      - devops-net


volumes:
  mysql-data:


networks:
  devops-net:
    driver: bridge
